"""new db

Revision ID: 0cccf6a5348b
Revises: 
Create Date: 2019-12-02 13:44:55.074405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cccf6a5348b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('WordSubject',
    sa.Column('wordsubject', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('wordsubject')
    )
    op.create_index(op.f('ix_WordSubject_wordsubject'), 'WordSubject', ['wordsubject'], unique=True)
    op.create_table('Word',
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('meaning', sa.String(length=64), nullable=True),
    sa.Column('word_subject', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['word_subject'], ['WordSubject.wordsubject'], ),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_index(op.f('ix_Word_word'), 'Word', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Word_word'), table_name='Word')
    op.drop_table('Word')
    op.drop_index(op.f('ix_WordSubject_wordsubject'), table_name='WordSubject')
    op.drop_table('WordSubject')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
